# Generated by Django 5.2.3 on 2025-06-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='voos.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='orign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='voos.airport'),
        ),
    ]
