# Generated by Django 5.2.3 on 2025-06-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0003_rename_orign_flight_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='voos.flight')),
            ],
        ),
    ]
